# Generated by Django 3.2.5 on 2021-07-15 18:28

import core.enums
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_dealerships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=50)),
                (
                    "carcase",
                    models.CharField(
                        choices=[
                            (core.enums.Carcase["SEDAN"], "sedan"),
                            (core.enums.Carcase["HATCHBACK"], "hatchback"),
                            (core.enums.Carcase["COUPE"], "coupe"),
                            (core.enums.Carcase["CABRIOLET"], "cabriolet"),
                            (core.enums.Carcase["LIMOUSINE"], "limousine"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (core.enums.State["NEW"], "NEW"),
                            (core.enums.State["WITH_MILEAGE"], "with mileage"),
                            (core.enums.State["BROKEN"], "broken"),
                            (core.enums.State["TOTAL"], "total"),
                        ],
                        max_length=25,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("foundation_time", models.DateTimeField(auto_now_add=True)),
                ("cars", models.ManyToManyField(to="provider.Car")),
                (
                    "customers",
                    models.ManyToManyField(to="car_dealerships.CarDealership"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("action_start_time", models.DateTimeField()),
                ("action_end_time", models.DateTimeField()),
                (
                    "discount_percentage",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("cars", models.ManyToManyField(to="provider.Car")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action",
                        to="provider.provider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("foundation_time", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturer",
                        to="car_dealerships.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars",
                to="provider.manufacturer",
            ),
        ),
    ]
