# Generated by Django 3.2.5 on 2021-07-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_dealerships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardealershipsale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_DS_buy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardealershipsale",
            name="sold_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold_car_DS",
                to="provider.car",
            ),
        ),
        migrations.AddField(
            model_name="cardealershipbuy",
            name="bought_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buy_car_DS",
                to="provider.car",
            ),
        ),
        migrations.AddField(
            model_name="cardealershipbuy",
            name="car_dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buy",
                to="car_dealerships.cardealership",
            ),
        ),
        migrations.AddField(
            model_name="cardealershipbuy",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_DS",
                to="provider.provider",
            ),
        ),
        migrations.AddField(
            model_name="cardealershipaction",
            name="car_dealership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="car_dealerships.cardealership",
            ),
        ),
        migrations.AddField(
            model_name="cardealershipaction",
            name="cars",
            field=models.ManyToManyField(related_name="action_car", to="provider.Car"),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="cars",
            field=models.ManyToManyField(
                through="car_dealerships.CarDealershipSale", to="provider.Car"
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="customers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_DS",
                to="car_dealerships.location",
            ),
        ),
    ]
