# Generated by Django 3.2.5 on 2021-07-19 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_dealerships', '0001_initial'),
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealershipsale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardealershipsale',
            name='sold_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='provider.car'),
        ),
        migrations.AddField(
            model_name='cardealershipbuy',
            name='bought_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provider.car'),
        ),
        migrations.AddField(
            model_name='cardealershipbuy',
            name='car_dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='car_dealerships.cardealership'),
        ),
        migrations.AddField(
            model_name='cardealershipbuy',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='provider.provider'),
        ),
        migrations.AddField(
            model_name='cardealershipaction',
            name='car_dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='car_dealerships.cardealership'),
        ),
        migrations.AddField(
            model_name='cardealershipaction',
            name='cars',
            field=models.ManyToManyField(related_name='_car_dealerships_cardealershipaction_cars_+', to='provider.Car'),
        ),
        migrations.AddField(
            model_name='cardealership',
            name='cars',
            field=models.ManyToManyField(through='car_dealerships.CarDealershipSale', to='provider.Car'),
        ),
        migrations.AddField(
            model_name='cardealership',
            name='customers',
            field=models.ManyToManyField(related_name='car_dealerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardealership',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='car_dealerships.location'),
        ),
    ]
