# Generated by Django 3.2.5 on 2021-08-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('car_dealerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecharacteristics',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider.car'),
        ),
        migrations.AddField(
            model_name='purchasecharacteristics',
            name='car_dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cars', to='car_dealerships.cardealership'),
        ),
        migrations.AddField(
            model_name='purchasecharacteristics',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showrooms_cars', to='provider.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city', 'street', 'building_number')},
        ),
        migrations.AddField(
            model_name='cardealershipsale',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provider.car'),
        ),
        migrations.AddField(
            model_name='cardealershipsale',
            name='car_dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='car_dealerships.cardealership'),
        ),
    ]
